apiVersion: v1
kind: Pod
metadata:
  name: pending
  namespace: cj-lab-trouble
spec:
  containers:
    - name: app
      image: busybox:1.36.1
      imagePullPolicy: Never
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100"
          memory: 1Gi
