apiVersion: v1
kind: Pod
metadata:
  name: traffic-client
  namespace: cj-lab-traffic
  labels:
    app: traffic-client
spec:
  restartPolicy: Never
  containers:
    - name: client
      image: busybox:1.36.1
      imagePullPolicy: Never
      command: ["/bin/sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          cpu: 50m
          memory: 32Mi
